In [1]:
import googlemaps
import os
import pandas as pd
import json
import csv
import os.path
import string
import re

googleMapsClient = googlemaps.Client(key=os.environ["GOOGLE_API_KEY"])

xls = pd.ExcelFile("/Users/covarrubiasr/Documents/SalesLogix/Sage_SALES_DATA_Research_Only_Cleaned.xlsx")

#View the Excel file's sheet names
xls.sheet_names

[u'FY16', u'FY17', u'FY18']

In [6]:
import googlemaps

import gmaps
gmaps.configure(api_key=os.environ["GOOGLE_API_KEY"])
#fig = gmaps.figure()
fig = gmaps.figure(center=[39.0997, -94.5786], zoom_level=4)
locations = [(46.1, 5.2), (46.2, 5.3), (46.3, 5.4)]
heatmap = gmaps.heatmap_layer(locations)
heatmap.max_intensity = 2
heatmap.point_radius = 3
heatmap.gradient = ['white', 'gray']
fig.add_layer(heatmap)

In [2]:
#load the xls file's sheet as a dataframe
df_sage_order_FY16 = xls.parse('FY16')
#df_sage_order_FY17 = xls.parse('FY17')
#df_sage_order_FY18 = xls.parse('FY18')


df_sage_order_FY16['Postal'] = df_sage_order_FY16['Postal'].astype(str).str.zfill(5)
#df_sage_order_FY17['Postal'] = df_sage_order_FY17['Postal'].astype(str).str.zfill(5)
#df_sage_order_FY18['Postal'] = df_sage_order_FY18['Postal'].astype(str).str.zfill(5)



df_sage_order_FY16.head()

,invoice_no,Line_No,Cust_Number,Invoice_Date,Invoice_Reference,Amount,Tax,region,territory,City,State,Postal,TAX_County,TAX_City,sage_address1,sage_address2,sage_address3,sage_address4,sage_address5
0,OP/I519210,1,UMA,2015-04-30,R33464,500.0,0.0,US,MR,AMHERST,MA,01002,HAMPSHIRE,AMHERST,UMASS AMHERST / LORI GOLDNER,DEPT OF PHYSICS/HASBROUCK LAB,666 NORTH PLEASANT STREET,"AMHERST, MA 01002",UNITED STATES
1,OP/I520643,1,WPI,2015-09-23,M520672,122.0,0.0,US,MS-AI,WORCESTER,MA,01605,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,JAGAN SRINIVASAN,60 PRESCOTT ST,"WORCESTER, MA 01605",UNITED STATES
2,OP/I521494,4,UMASS,2015-12-03,521474,480.0,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
3,OP/I521494,5,UMASS,2015-12-03,521474,14036.0,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
4,OP/I521494,6,UMASS,2015-12-03,521474,15.0,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES

In [3]:
#select Unique Zip Codes 
zipCodes = df_sage_order_FY16.Postal.unique()

#For each unique zipcode, find the total purchases
df_sage_order_FY16[df_sage_order_FY16.Postal.isin(zipCodes)]

,invoice_no,Line_No,Cust_Number,Invoice_Date,Invoice_Reference,Amount,Tax,region,territory,City,State,Postal,TAX_County,TAX_City,sage_address1,sage_address2,sage_address3,sage_address4,sage_address5
0,OP/I519210,1,UMA,2015-04-30,R33464,500.00,0.0,US,MR,AMHERST,MA,01002,HAMPSHIRE,AMHERST,UMASS AMHERST / LORI GOLDNER,DEPT OF PHYSICS/HASBROUCK LAB,666 NORTH PLEASANT STREET,"AMHERST, MA 01002",UNITED STATES
1,OP/I520643,1,WPI,2015-09-23,M520672,122.00,0.0,US,MS-AI,WORCESTER,MA,01605,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,JAGAN SRINIVASAN,60 PRESCOTT ST,"WORCESTER, MA 01605",UNITED STATES
2,OP/I521494,4,UMASS,2015-12-03,521474,480.00,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
3,OP/I521494,5,UMASS,2015-12-03,521474,14036.00,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
4,OP/I521494,6,UMASS,2015-12-03,521474,15.00,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
5,OP/I521840,1,UMASS,2016-01-13,521474/1,18050.00,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
6,OP/I521840,3,UMASS,2016-01-13,521474/1,416.00,0.0,US,TPP,WORCESTER,MA,01605,WORCESTER,WORCESTER,UMASS MED / ALBERT SHERMAN CTR,GRUNWALD LAB/AS4-1017,368 PLANTATION STREET,"WORCESTER, MA 01605",UNITED STATES
7,OP/I522659,1,WPI,2016-03-24,521536,9561.33,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
8,OP/I522659,2,WPI,2016-03-24,521536,2113.89,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
9,OP/I522659,3,WPI,2016-03-24,521536,956.04,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
10,OP/I522659,4,WPI,2016-03-24,521536,855.60,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
11,OP/I522659,5,WPI,2016-03-24,521536,855.60,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
12,OP/I522659,6,WPI,2016-03-24,521536,1006.26,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
13,OP/I522659,7,WPI,2016-03-24,521536,862.11,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
14,OP/I522659,8,WPI,2016-03-24,521536,53993.01,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
15,OP/I522659,9,WPI,2016-03-24,521536,1527.60,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
16,OP/I522659,10,WPI,2016-03-24,521536,247.00,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
17,OP/I522659,11,WPI,2016-03-24,521536,1711.20,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
18,OP/I522659,17,WPI,2016-03-24,521536,20.00,0.0,US,TPP,WORCESTER,MA,01609,WORCESTER,WORCESTER,WORCESTER POLYTECHNIC INST,ME DEPT.,100 INSTITUTE ROAD WASHBURN,"WORCESTER, MA 01609",UNITED STATES
19,OP/I520078,1,FLUID,2015-07-30,R33430,525.00,0.0,US,TG,CONCORD,MA,01742,MIDDLESEX,CONCORD,FLUIDIGM CORPORATION,7000 SHORELINE AV. STE. 150,"CONCORD, MA 01742",,UNITED STATES
20,OP/I520078,10,FLUID,2015-07-30,R33430,8.00,0.0,US,TG,CONCORD,MA,01742,MIDDLESEX,CONCORD,FLUIDIGM CORPORATION,7000 SHORELINE AV. STE. 150,"CONCORD, MA 01742",,UNITED STATES
21,OP/C501111,1,CALIPER,2015-04-21,CN502831,-28468.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
22,OP/C501115,1,CALIPER,2015-05-28,CN502846,-14405.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
23,OP/C501130,1,CALIPER,2015-06-10,CN502861,-14405.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
24,OP/C501131,1,CALIPER,2015-06-11,CN502862,-28468.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
25,OP/C501138,1,CALIPER,2015-07-24,CN502871,-14406.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
26,OP/C501139,1,CALIPER,2015-07-24,CN502872,-28468.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
27,OP/C501143,1,CALIPER,2015-08-21,CN502881,-9207.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
28,OP/C501165,1,CALIPER,2015-10-07,CN502911,-31406.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
29,OP/C501168,1,CALIPER,2015-10-14,CN502915,-31406.00,0.0,US,TCN,HOPKINTON,MA,01748,MIDDLESEX,HOPKINTON,CALIPER LIFE SCIENCES,68 ELM STREET,ATTN: ACCOUNTS PAYABLE,"HOPKINTON, MA 01748",UNITED STATES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,OP/I519454,12,WASH,2015-05-28,M519128,10150.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO: F74336,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4971,OP/I519454,13,WASH,2015-05-28,M519128,9252.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO: F74336,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4972,OP/I519455,1,WASH,2015-05-28,M519129,23850.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4973,OP/I519455,2,WASH,2015-05-28,M519129,225.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4974,OP/I519455,3,WASH,2015-05-28,M519129,608.23,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4975,OP/I519455,4,WASH,2015-05-28,M519129,1997.28,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4976,OP/I519455,5,WASH,2015-05-28,M519129,1512.34,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4977,OP/I519455,6,WASH,2015-05-28,M519129,189.04,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4978,OP/I519455,7,WASH,2015-05-28,M519129,41.10,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4979,OP/I519455,8,WASH,2015-05-28,M519129,3147.98,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4980,OP/I519455,9,WASH,2015-05-28,M519129,11704.23,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4981,OP/I519455,10,WASH,2015-05-28,M519129,854.80,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4982,OP/I519455,11,WASH,2015-05-28,M519129,4608.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4983,OP/I519455,12,WASH,2015-05-28,M519129,10150.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4984,OP/I519455,13,WASH,2015-05-28,M519129,4476.80,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4985,OP/I519456,1,WASH,2015-05-28,M519130,11486.67,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4986,OP/I519456,2,WASH,2015-05-28,M519130,11388.99,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4987,OP/I519456,3,WASH,2015-05-28,M519130,11109.84,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4988,OP/I519456,4,WASH,2015-05-28,M519130,405.35,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4989,OP/I519456,5,WASH,2015-05-28,M519130,55980.40,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4990,OP/I519456,6,WASH,2015-05-28,M519130,293.03,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4991,OP/I519456,7,WASH,2015-05-28,M519130,781.41,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4992,OP/I519456,8,WASH,2015-05-28,M519130,903.50,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4993,OP/I519456,9,WASH,2015-05-28,M519130,4476.80,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4994,OP/I519456,10,WASH,2015-05-28,M519130,10150.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4995,OP/I519456,11,WASH,2015-05-28,M519130,1179.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4996,OP/I519456,14,WASH,2015-05-28,M519130,5260.00,0.0,US,KJ,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV/PO#F743363,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,PULLMAN WA 99164-1120,UNITED STATES
4997,OP/I521102,1,WASH,2015-10-29,M521095,3876.00,0.0,US,AR,PULLMAN,WA,99164-1120,WHITMAN,PULLMAN,WASHINGTON STATE UNIV,CENTRAL RECEIVING AND DELIVERY,100 DAIRY ROAD,"PULLMAN, WA 99164-1120",UNITED STATES
4998,OP/I522575,1,UALASKA,2016-03-17,522197,36628.20,0.0,US,CJC,FAIRBANKS,AK,99775-7320,FAIRBANKS NORTH STAR,FAIRBANKS,UNIVERSITY OF ALASKA FAIRBANKS,ROBERTA GREENLEE,GEOGRAPHICAL INST. 903 KOYUKUK,"FAIRBANKS, AK 99775-7320",UNITED STATES
4999,OP/I522575,2,UALASKA,2016-03-17,522197,15.00,0.0,US,CJC,FAIRBANKS,AK,99775-7320,FAIRBANKS NORTH STAR,FAIRBANKS,UNIVERSITY OF ALASKA FAIRBANKS,ROBERTA GREENLEE,GEOGRAPHICAL INST. 903 KOYUKUK,"FAIRBANKS, AK 99775-7320",UNITED STATES

In [117]:
#add the amount for each zipcode
#totalAmountPerZipCode = df_sage_order_FY16[df_sage_order_FY16.Postal.isin(zipCodes)['Amount'].sum()
#df[df.name.isin(value_list)]

#print df.groupby('User_ID')['clicks'].sum().reset_index()
test = df_sage_order_FY16.groupby(['Postal'])['Amount'].sum().reset_index()
test.head()

#df_sage_order_FY16.groupby('Postal')['Amount'])
#df_sage_order_FY16.groupby(['Postal']).sum()['']

  Postal      Amount
0  01002      500.00
1  01605    33119.00
2  01609    73709.64
3  01742      533.00
4  01748  4188907.24

In [25]:
#sum all sales for a given zipcode (first five digits of zipcode)
#postalcodes_Temp_FY16 = (df_sage_order_FY16['Postal']).tolist()
#amountSales_Temp_FY16 = (df_sage_order_FY16['Amount']).tolist()
#dateSales_Temp_FY16 = (df_sage_order_FY16['Invoice_Date']).tolist()

#samecodes = []
#for id,zcode in enumerate(df_sage_order_FY16['Postal'][0:15]):
    
#    print(df_sage_order_FY16['Postal'][id])
#    if str(df_sage_order_FY16['Postal'][id]) == str(df_sage_order_FY16['Postal'][id+1]):
#        print(id,df_sage_order_FY16['Postal'][id])
#        print(id+1,df_sage_order_FY16['Postal'][id+1])
#        samecodes.append(id)
        
#print(samecodes)

#df_sage_order_FY16['Amount'][1:6].sum()

#test = df_sage_order_FY16.groupby('Postal')

#test.head()

zipCodes

In [7]:
#make a list of all zipcodes
postalcodes_FY16 = (df_sage_order_FY16['Postal']).tolist()
amountSales_FY16 = (df_sage_order_FY16['Amount']).tolist()
dateSales_FY16 = (df_sage_order_FY16['Invoice_Date']).tolist()

#postalcodes_FY17 = (df_sage_order_FY17['Postal']).tolist()
#amountSales_FY17 = (df_sage_order_FY17['Amount']).tolist()
#dateSales_FY17 = (df_sage_order_FY17['Invoice_Date']).tolist()

#postalcodes_FY18 = (df_sage_order_FY18['Postal']).tolist()
#amountSales_FY18 = (df_sage_order_FY18['Amount']).tolist()
#dateSales_FY18 = (df_sage_order_FY18['Invoice_Date']).tolist()

print(postalcodes_FY16[4242:4252],amountSales_FY16[4242:4252],dateSales_FY16[4242:4252])

(['97186', '97186', '97186', '97186', '97186', '97186', '97186', '97186', '97186', '97186'], [215.0, 1812.0, 1800.0, 605.0, 1170.0, 2143.0, 525.0, 1756.0, 2117.0, 475.0], [Timestamp('2015-08-13 00:00:00'), Timestamp('2015-08-20 00:00:00'), Timestamp('2015-08-27 00:00:00'), Timestamp('2015-09-03 00:00:00'), Timestamp('2015-09-08 00:00:00'), Timestamp('2015-09-23 00:00:00'), Timestamp('2015-10-07 00:00:00'), Timestamp('2015-10-07 00:00:00'), Timestamp('2015-10-09 00:00:00'), Timestamp('2015-10-29 00:00:00')])

In [28]:
out_filenames_data = ["Sales_US_FY16_all.csv","Sales_US_FY17.csv","Sales_US_FY18.csv"]

if os.path.isfile('/Users/covarrubiasr/Documents/SalesLogix/Sales_US_FY16_all.csv'): 
    print("filename with lat and long exist \n")
    lat_lng_potential = pd.read_csv('/Users/covarrubiasr/Documents/SalesLogix/Sales_US_FY16_all.csv')
    print("latitude and longitude filename read")

else:
    coords = []

    calls = 0
    prev_zipcode = ""


    for idx, zipcode in enumerate(postalcodes_FY16):
        #print(zipcode,"is variable type", type(zipcode))
        #print(prev_zipcode,"is variable type", type(zipcode))
        #print(prev_zipcode, zipcode,idx)

        if zipcode == '97186':
            continue
        print(idx, zipcode,amountSales_FY16[idx],dateSales_FY16[idx])
        if idx == 0:
            print(len(zipcode))
            print(type(zipcode))
            temp = googleMapsClient.geocode(zipcode)
            print(temp)
            calls = calls+1
            lat = temp[0]['geometry']['location']['lat']
            lng = temp[0]['geometry']['location']['lng']
            coords.append((zipcode,lat,lng,amountSales_FY16[idx],dateSales_FY16[idx]))
            #print("inside indx 0")
        elif zipcode != prev_zipcode:
            temp = googleMapsClient.geocode(zipcode)
            calls = calls+1
            lat = temp[0]['geometry']['location']['lat']
            lng = temp[0]['geometry']['location']['lng']
            coords.append((zipcode,lat,lng,amountSales_FY16[idx],dateSales_FY16[idx]))
            #print("inside zipcode not equal prev_zipcode",lat,lng)
        else:
            coords.append((zipcode,lat,lng,amountSales_FY16[idx],dateSales_FY16[idx]))
            #print("inside else", lat,lng)
        prev_zipcode = zipcode


        #if idx == 4240:
        #    with open(out_filenames_data[0],'wb') as out:
        #       csv_out=csv.writer(out)
        #        csv_out.writerow(['Postal','Latitute','Longitude','Amount','Invoice_Date'])
        #        for row in coords:
        #           #row[4] = row[4].strftime('%Y-%m-%d %H:%M:%S')
        #           csv_out.writerow(row)
        #


    with open(out_filenames_data[0],'wb') as out:
        csv_out=csv.writer(out)
        csv_out.writerow(['Postal','Latitude','Longitude','Amount','Invoice_Date'])
        for row in coords:
            csv_out.writerow(row)

        
#for val in coords:
#    print(val)
#print(calls)

(30, '97330', 122.0, Timestamp('2015-07-29 00:00:00'))
(31, '97330', 498.75, Timestamp('2015-09-28 00:00:00'))
(32, '97330', 1497.2, Timestamp('2015-09-28 00:00:00'))
(33, '97330', 10640.0, Timestamp('2015-09-28 00:00:00'))
(34, '97701', 6337.0, Timestamp('2016-01-26 00:00:00'))
(35, '98105', 1250.0, Timestamp('2015-06-17 00:00:00'))
(36, '98108', 1380.0, Timestamp('2015-07-16 00:00:00'))
(37, '98109', 15.0, Timestamp('2016-01-07 00:00:00'))
(38, '98109', 44.78, Timestamp('2016-02-10 00:00:00'))
(39, '98109', 107.13, Timestamp('2016-02-10 00:00:00'))
(40, '98109', 122.0, Timestamp('2016-02-10 00:00:00'))
(41, '98109', 125.57, Timestamp('2016-02-10 00:00:00'))
(42, '98109', 196.69, Timestamp('2016-02-10 00:00:00'))
(43, '98109', 206.35, Timestamp('2016-02-10 00:00:00'))
(44, '98109', 251.14, Timestamp('2016-02-10 00:00:00'))
(45, '98109', 698.97, Timestamp('2016-02-10 00:00:00'))
(46, '98109', 725.31, Timestamp('2016-02-10 00:00:00'))
(47, '98109', 895.66, Timestamp('2016-02-10 00:00:00'))
(48, '98109', 1066.01, Timestamp('2016-02-10 00:00:00'))
(49, '98109', 1176.65, Timestamp('2016-02-10 00:00:00'))
(50, '98109', 1469.06, Timestamp('2016-02-10 00:00:00'))
(51, '98109', 8450.0, Timestamp('2016-01-07 00:00:00'))
(52, '98109', 8759.93, Timestamp('2016-02-10 00:00:00'))
(53, '98109', 8960.0, Timestamp('2016-01-28 00:00:00'))
(54, '98109', 8960.0, Timestamp('2016-01-28 00:00:00'))
(55, '98109', 8960.0, Timestamp('2016-03-15 00:00:00'))
(56, '98109', 8960.0, Timestamp('2016-03-15 00:00:00'))
(57, '98109', 10489.0, Timestamp('2015-11-05 00:00:00'))
(58, '98109', 10489.0, Timestamp('2015-11-05 00:00:00'))
(59, '98109', 10489.0, Timestamp('2015-11-05 00:00:00'))
(60, '98109', 10489.0, Timestamp('2015-11-05 00:00:00'))
(61, '98109', 24988.97, Timestamp('2016-02-10 00:00:00'))
(62, '98195', 493.0, Timestamp('2015-08-10 00:00:00'))
(63, '98195', 493.5, Timestamp('2015-09-23 00:00:00'))
(64, '98195', 530.0, Timestamp('2015-07-10 00:00:00'))
(65, '98195', 536.0, Timestamp('2015-07-10 00:00:00'))
(66, '98195', 1900.0, Timestamp('2015-07-10 00:00:00'))
(67, '98195', 10304.0, Timestamp('2015-08-10 00:00:00'))
(68, '98195', 17812.0, Timestamp('2015-07-10 00:00:00'))
(69, '98195', 32108.52, Timestamp('2015-09-23 00:00:00'))
(70, '99164', 15.0, Timestamp('2016-02-10 00:00:00'))
(71, '99164', 1045.2, Timestamp('2016-02-10 00:00:00'))
(72, '99164', 19673.5, Timestamp('2016-02-10 00:00:00'))
(73, '02139-4307', 15.0, Timestamp('2015-12-03 00:00:00'))
(74, '02139-4307', 95.5, Timestamp('2015-06-17 00:00:00'))
(75, '02139-4307', 95.5, Timestamp('2015-10-12 00:00:00'))
(76, '02139-4307', 429.75, Timestamp('2015-06-17 00:00:00'))
(77, '02139-4307', 429.75, Timestamp('2015-10-12 00:00:00'))
(78, '02139-4307', 472.5, Timestamp('2015-05-20 00:00:00'))
(79, '02139-4307', 563.45, Timestamp('2015-06-17 00:00:00'))
(80, '02139-4307', 563.45, Timestamp('2015-10-12 00:00:00'))
(81, '02139-4307', 783.1, Timestamp('2015-06-17 00:00:00'))
(82, '02139-4307', 783.1, Timestamp('2015-06-17 00:00:00'))
(83, '02139-4307', 783.1, Timestamp('2015-06-17 00:00:00'))
(84, '02139-4307', 783.1, Timestamp('2015-10-12 00:00:00'))
(85, '02139-4307', 783.1, Timestamp('2015-10-12 00:00:00'))
(86, '02139-4307', 783.1, Timestamp('2015-10-12 00:00:00'))
(87, '02139-4307', 1505.08, Timestamp('2015-06-17 00:00:00'))
(88, '02139-4307', 1505.08, Timestamp('2015-10-12 00:00:00'))
(89, '02139-4307', 1744.2, Timestamp('2015-04-27 00:00:00'))
(90, '02139-4307', 3117.12, Timestamp('2015-06-17 00:00:00'))
(91, '02139-4307', 3117.12, Timestamp('2015-10-12 00:00:00'))
(92, '02139-4307', 7544.5, Timestamp('2015-06-17 00:00:00'))
(93, '02139-4307', 7544.5, Timestamp('2015-10-12 00:00:00'))
(94, '02139-4307', 10080.0, Timestamp('2015-05-20 00:00:00'))
(95, '02139-4307', 30670.75, Timestamp('2015-12-03 00:00:00'))
(96, '02139-4307', 30801.62, Timestamp('2015-06-17 00:00:00'))
(97, '02139-4307', 30801.62, Timestamp('2015-10-12 00:00:00'))
(98, '02142-1493', 3121.0, Timestamp('2015-06-17 00:00:00'))
(99, '02142-1493', 28830.0, Timestamp('2016-01-27 00:00:00'))
(100, '02322-0518', -24185.81, Timestamp('2015-09-30 00:00:00'))
(101, '02322-0518', -14486.0, Timestamp('2015-12-04 00:00:00'))
(102, '02322-0518', -9932.5, Timestamp('2015-08-27 00:00:00'))
(103, '02322-0518', -418.65, Timestamp('2015-09-24 00:00:00'))
(104, '02322-0518', -183.0, Timestamp('2015-10-26 00:00:00'))
(105, '02322-0518', 15.0, Timestamp('2016-03-24 00:00:00'))
(106, '02322-0518', 64.4, Timestamp('2015-10-26 00:00:00'))
(107, '02322-0518', 112.5, Timestamp('2015-10-26 00:00:00'))
(108, '02322-0518', 180.6, Timestamp('2015-10-26 00:00:00'))
(109, '02322-0518', 402.5, Timestamp('2015-06-22 00:00:00'))
(110, '02322-0518', 717.5, Timestamp('2015-06-22 00:00:00'))
(111, '02322-0518', 1125.6, Timestamp('2015-08-19 00:00:00'))
(112, '02322-0518', 1728.0, Timestamp('2015-04-30 00:00:00'))
(113, '02322-0518', 1728.0, Timestamp('2015-06-22 00:00:00'))
(114, '02322-0518', 3426.75, Timestamp('2015-06-22 00:00:00'))
(115, '02322-0518', 6316.2, Timestamp('2015-08-19 00:00:00'))
(116, '02322-0518', 6398.0, Timestamp('2015-06-22 00:00:00'))
(117, '02322-0518', 7672.0, Timestamp('2015-08-27 00:00:00'))
(118, '02322-0518', 7672.0, Timestamp('2015-10-28 00:00:00'))
(119, '02322-0518', 9207.0, Timestamp('2016-03-24 00:00:00'))
(120, '02322-0518', 13624.65, Timestamp('2015-08-14 00:00:00'))
(121, '02322-0518', 13624.65, Timestamp('2015-08-19 00:00:00'))
(122, '02322-0518', 26722.0, Timestamp('2015-10-20 00:00:00'))
(123, '02421-7728', 583.0, Timestamp('2016-03-22 00:00:00'))
(124, '02454-9110', 8.0, Timestamp('2016-01-13 00:00:00'))
(125, '02454-9110', 148.2, Timestamp('2016-01-13 00:00:00'))
(126, '05405-0110', 14480.0, Timestamp('2016-01-27 00:00:00'))
(127, '06269-3046', 20.0, Timestamp('2015-11-20 00:00:00'))
(128, '06269-3046', 86.7, Timestamp('2015-11-20 00:00:00'))
(129, '06269-3046', 586.5, Timestamp('2015-12-10 00:00:00'))
(130, '06269-3046', 586.5, Timestamp('2015-12-10 00:00:00'))
(131, '06269-3046', 710.6, Timestamp('2015-11-20 00:00:00'))
(132, '06269-3046', 710.6, Timestamp('2015-11-20 00:00:00'))
(133, '06269-3046', 787.95, Timestamp('2015-11-20 00:00:00'))
(134, '06269-3046', 866.0, Timestamp('2015-11-20 00:00:00'))
(135, '06269-3046', 938.4, Timestamp('2015-11-20 00:00:00'))
(136, '06269-3046', 1173.0, Timestamp('2015-11-20 00:00:00'))
(137, '06269-3046', 1366.8, Timestamp('2015-11-20 00:00:00'))
(138, '06269-3046', 6983.6, Timestamp('2015-11-20 00:00:00'))
(139, '06269-3046', 23689.5, Timestamp('2015-11-20 00:00:00'))
(140, '06269-3125', 20.0, Timestamp('2015-06-05 00:00:00'))
(141, '06269-3125', 110.0, Timestamp('2015-06-05 00:00:00'))
(142, '06269-3125', 160.0, Timestamp('2015-06-05 00:00:00'))
(143, '06269-3125', 200.0, Timestamp('2015-06-05 00:00:00'))
(144, '06269-3125', 453.15, Timestamp('2015-06-05 00:00:00'))
(145, '06269-3125', 7731.1, Timestamp('2015-06-05 00:00:00'))
(146, '06269-3125', 13406.4, Timestamp('2015-06-05 00:00:00'))
(147, '06269-3125', 24047.35, Timestamp('2015-06-05 00:00:00'))
(148, '06269-3149', 2840.0, Timestamp('2015-08-20 00:00:00'))
(149, '06269-6080', -1173.0, Timestamp('2015-11-25 00:00:00'))
(150, '08102-1656', 15.0, Timestamp('2016-03-03 00:00:00'))
(151, '08102-1656', 161.25, Timestamp('2016-03-03 00:00:00'))
(152, '08102-1656', 197.43, Timestamp('2016-03-03 00:00:00'))
(153, '08102-1656', 252.72, Timestamp('2016-03-03 00:00:00'))
(154, '08102-1656', 278.46, Timestamp('2016-03-03 00:00:00'))
(155, '08102-1656', 579.75, Timestamp('2016-03-03 00:00:00'))
(156, '08102-1656', 731.64, Timestamp('2016-03-03 00:00:00'))
(157, '08102-1656', 731.64, Timestamp('2016-03-03 00:00:00'))
(158, '08102-1656', 731.64, Timestamp('2016-03-03 00:00:00'))
(159, '08102-1656', 774.54, Timestamp('2016-03-03 00:00:00'))
(160, '08102-1656', 777.75, Timestamp('2016-03-03 00:00:00'))
(161, '08102-1656', 818.22, Timestamp('2016-03-03 00:00:00'))
(162, '08102-1656', 47163.75, Timestamp('2016-03-03 00:00:00'))
(163, '08854-5602', -1901.74, Timestamp('2016-01-13 00:00:00'))
(164, '10003-6630', 273.0, Timestamp('2015-04-13 00:00:00'))
(165, '10016-6481', 12.0, Timestamp('2015-11-10 00:00:00'))
(166, '10016-6481', 710.0, Timestamp('2015-04-13 00:00:00'))
(167, '10016-6481', 1420.0, Timestamp('2015-11-10 00:00:00'))
(168, '10016-6481', 1750.0, Timestamp('2015-04-13 00:00:00'))
(169, '10016-6481', 1750.0, Timestamp('2015-05-28 00:00:00'))
(170, '10016-6481', 4141.0, Timestamp('2015-05-28 00:00:00'))
(171, '10065-6321', 90.0, Timestamp('2016-02-23 00:00:00'))

(172, '10065-6321', 231.83, Timestamp('2016-02-23 00:00:00'))
(173, '10065-6321', 309.38, Timestamp('2016-02-23 00:00:00'))
(174, '10065-6321', 327.08, Timestamp('2016-02-23 00:00:00'))
(175, '10065-6321', 342.26, Timestamp('2016-02-23 00:00:00'))
(176, '10065-6321', 378.51, Timestamp('2016-02-23 00:00:00'))
(177, '10065-6321', 378.51, Timestamp('2016-02-23 00:00:00'))
(178, '10065-6321', 464.49, Timestamp('2016-02-23 00:00:00'))
(179, '10065-6321', 499.06, Timestamp('2016-02-23 00:00:00'))
(180, '10065-6321', 709.88, Timestamp('2016-02-23 00:00:00'))
(181, '10065-6321', 755.63, Timestamp('2016-02-23 00:00:00'))
(182, '10065-6321', 850.59, Timestamp('2016-02-23 00:00:00'))
(183, '10065-6321', 1083.26, Timestamp('2016-02-23 00:00:00'))
(184, '10065-6321', 1159.13, Timestamp('2016-02-23 00:00:00'))
(185, '10065-6321', 1306.65, Timestamp('2016-02-26 00:00:00'))
(186, '10065-6321', 1423.0, Timestamp('2016-02-23 00:00:00'))
(187, '10065-6321', 1470.19, Timestamp('2016-02-23 00:00:00'))
(188, '10065-6321', 1504.75, Timestamp('2016-02-23 00:00:00'))
(189, '10065-6321', 5337.88, Timestamp('2016-02-23 00:00:00'))
(190, '10065-6321', 6322.5, Timestamp('2016-02-23 00:00:00'))
(191, '10065-6321', 7530.0, Timestamp('2016-02-23 00:00:00'))
(192, '10065-6321', 9260.36, Timestamp('2016-02-23 00:00:00'))
(193, '10065-6321', 9957.52, Timestamp('2016-02-23 00:00:00'))
(194, '10065-6321', 11721.92, Timestamp('2016-02-23 00:00:00'))
(195, '10065-6321', 11850.89, Timestamp('2016-02-23 00:00:00'))
(196, '10065-6321', 12149.32, Timestamp('2016-02-23 00:00:00'))
(197, '10065-6321', 12149.32, Timestamp('2016-02-23 00:00:00'))
(198, '10065-6321', 12253.01, Timestamp('2016-02-23 00:00:00'))
(199, '10065-6321', 18572.98, Timestamp('2016-02-23 00:00:00'))
(200, '10065-6321', 19776.78, Timestamp('2016-02-23 00:00:00'))
(201, '10065-6321', 34947.95, Timestamp('2016-02-23 00:00:00'))
(202, '10065-6321', 101061.37, Timestamp('2016-02-23 00:00:00'))
(203, '11747-2112', 15.0, Timestamp('2015-12-18 00:00:00'))
(204, '11747-2112', 15.0, Timestamp('2015-12-23 00:00:00'))
(205, '11747-2112', 15.0, Timestamp('2016-01-19 00:00:00'))
(206, '11747-2112', 750.0, Timestamp('2015-08-28 00:00:00'))
(207, '11747-2112', 7150.0, Timestamp('2016-03-03 00:00:00'))
(208, '11747-2112', 7840.0, Timestamp('2015-05-27 00:00:00'))
(209, '11747-2112', 7840.0, Timestamp('2015-06-26 00:00:00'))
(210, '11747-2112', 8064.0, Timestamp('2016-01-19 00:00:00'))
(211, '11747-2112', 9100.0, Timestamp('2015-09-21 00:00:00'))
(212, '11747-2112', 9360.0, Timestamp('2015-07-07 00:00:00'))
(213, '11747-2112', 9360.0, Timestamp('2015-07-07 00:00:00'))
(214, '11747-2112', 11700.0, Timestamp('2015-09-23 00:00:00'))
(215, '11747-2112', 13300.0, Timestamp('2015-12-18 00:00:00'))
(216, '11747-2112', 13300.0, Timestamp('2015-12-23 00:00:00'))
(217, '11747-2112', 13923.0, Timestamp('2015-06-08 00:00:00'))
(218, '12180-3590', 8.0, Timestamp('2016-01-13 00:00:00'))
(219, '12180-3590', 30.0, Timestamp('2015-10-21 00:00:00'))
(220, '12180-3590', 108.9, Timestamp('2015-10-21 00:00:00'))
(221, '12180-3590', 482.4, Timestamp('2015-10-21 00:00:00'))
(222, '12180-3590', 993.6, Timestamp('2015-10-21 00:00:00'))
(223, '12180-3590', 1043.1, Timestamp('2015-10-21 00:00:00'))
(224, '12180-3590', 1043.1, Timestamp('2015-10-21 00:00:00'))
(225, '12180-3590', 1043.1, Timestamp('2015-10-21 00:00:00'))
(226, '12180-3590', 1545.0, Timestamp('2016-01-13 00:00:00'))
(227, '12180-3590', 2500.0, Timestamp('2015-10-21 00:00:00'))
(228, '12180-3590', 11333.9, Timestamp('2015-10-21 00:00:00'))
(229, '12180-3590', 12196.65, Timestamp('2016-02-24 00:00:00'))
(230, '12180-3590', 17357.0, Timestamp('2015-10-21 00:00:00'))
(231, '13153-0220', -1731.6, Timestamp('2016-02-22 00:00:00'))
(232, '13153-0220', -527.16, Timestamp('2016-02-22 00:00:00'))
(233, '13153-0220', -358.8, Timestamp('2016-02-22 00:00:00'))
(234, '13153-0220', -338.56, Timestamp('2016-02-22 00:00:00'))
(235, '13153-0220', -229.2, Timestamp('2016-02-22 00:00:00'))
(236, '13153-0220', 338.56, Timestamp('2015-06-25 00:00:00'))
(237, '13153-0220', 358.8, Timestamp('2015-06-25 00:00:00'))
(238, '13153-0220', 527.16, Timestamp('2015-06-25 00:00:00'))
(239, '13153-0220', 1731.6, Timestamp('2015-06-25 00:00:00'))
(240, '13153-0220', 11449.4, Timestamp('2015-06-25 00:00:00'))
(241, '19104-6018', 9.0, Timestamp('2015-04-23 00:00:00'))
(242, '19104-6018', 1420.0, Timestamp('2015-04-23 00:00:00'))
(243, '19104-6058', 280.0, Timestamp('2015-06-05 00:00:00'))
(244, '19104-6085', 15.0, Timestamp('2016-02-19 00:00:00'))
(245, '19104-6085', 31835.3, Timestamp('2016-02-19 00:00:00'))
(246, '19104-6323', 852.0, Timestamp('2015-07-07 00:00:00'))
(247, '19104-6323', 852.75, Timestamp('2015-07-07 00:00:00'))
(248, '19104-6323', 1592.0, Timestamp('2015-09-25 00:00:00'))
(249, '19104-6323', 10770.0, Timestamp('2015-07-07 00:00:00'))
(250, '19104-6323', 18666.75, Timestamp('2015-07-07 00:00:00'))
(251, '19107-5587', -11600.0, Timestamp('2015-07-03 00:00:00'))
(252, '19107-5587', -6925.57, Timestamp('2015-10-28 00:00:00'))
(253, '19107-5587', 96.6, Timestamp('2015-06-17 00:00:00'))
(254, '19107-5587', 112.0, Timestamp('2015-06-17 00:00:00'))
(255, '19107-5587', 184.0, Timestamp('2015-06-17 00:00:00'))
(256, '19107-5587', 288.0, Timestamp('2015-06-17 00:00:00'))
(257, '19107-5587', 480.0, Timestamp('2015-06-17 00:00:00'))
(258, '19107-5587', 480.0, Timestamp('2015-06-17 00:00:00'))
(259, '19107-5587', 592.0, Timestamp('2015-06-17 00:00:00'))
(260, '19107-5587', 928.0, Timestamp('2015-06-17 00:00:00'))
(261, '19107-5587', 952.0, Timestamp('2015-06-17 00:00:00'))
(262, '19107-5587', 1312.0, Timestamp('2015-06-17 00:00:00'))
(263, '19107-5587', 5250.0, Timestamp('2015-06-17 00:00:00'))
(264, '19107-5587', 8184.0, Timestamp('2015-06-17 00:00:00'))
(265, '19107-5587', 8768.0, Timestamp('2015-06-17 00:00:00'))
(266, '19107-5587', 11600.0, Timestamp('2015-07-07 00:00:00'))
(267, '20392-5420', 10.0, Timestamp('2016-03-23 00:00:00'))
(268, '20392-5420', 10.0, Timestamp('2016-03-23 00:00:00'))
(269, '20392-5420', 10.0, Timestamp('2016-03-23 00:00:00'))
(270, '20392-5420', 11200.0, Timestamp('2016-03-23 00:00:00'))
(271, '20392-5420', 11200.0, Timestamp('2016-03-23 00:00:00'))
(272, '20392-5420', 11200.0, Timestamp('2016-03-23 00:00:00'))
(273, '20742-3142', -4078.7, Timestamp('2015-12-03 00:00:00'))
(274, '20742-3142', -544.76, Timestamp('2016-02-19 00:00:00'))
(275, '20783-1138', 35088.9, Timestamp('2016-01-07 00:00:00'))
(276, '20815-6789', -3851.43, Timestamp('2015-07-24 00:00:00'))
(277, '20815-6789', -777.48, Timestamp('2015-07-24 00:00:00'))
(278, '20815-6789', -130.39, Timestamp('2015-07-24 00:00:00'))
(279, '20899-0001', 9.24, Timestamp('2015-09-17 00:00:00'))
(280, '20899-0001', 101.64, Timestamp('2015-09-17 00:00:00'))
(281, '20899-0001', 110.88, Timestamp('2015-09-17 00:00:00'))
(282, '20899-0001', 509.88, Timestamp('2015-09-17 00:00:00'))
(283, '20899-0001', 556.92, Timestamp('2015-09-17 00:00:00'))
(284, '20899-0001', 927.36, Timestamp('2015-09-17 00:00:00'))
(285, '20899-0001', 973.56, Timestamp('2015-09-17 00:00:00'))
(286, '20899-0001', 973.56, Timestamp('2015-09-17 00:00:00'))
(287, '20899-0001', 1097.04, Timestamp('2015-09-17 00:00:00'))
(288, '20899-0001', 2796.36, Timestamp('2015-09-17 00:00:00'))
(289, '20899-0001', 2796.36, Timestamp('2015-09-17 00:00:00'))
(290, '20899-0001', 3059.28, Timestamp('2015-09-17 00:00:00'))
(291, '20899-0001', 12303.48, Timestamp('2015-09-17 00:00:00'))
(292, '20899-0001', 46139.7, Timestamp('2015-09-17 00:00:00'))
(293, '20899-6203', 1214.0, Timestamp('2015-06-11 00:00:00'))
(294, '21236-2401', 8.0, Timestamp('2015-09-03 00:00:00'))
(295, '21236-2401', 144.0, Timestamp('2015-09-03 00:00:00'))
(296, '30314-4399', -1608.0, Timestamp('2015-11-18 00:00:00'))
(297, '33470-4930', 2200.0, Timestamp('2015-07-14 00:00:00'))
(298, '37209-1561', 26135.36, Timestamp('2015-06-11 00:00:00'))
(299, '37996-4542', 15.0, Timestamp('2016-03-15 00:00:00'))
(300, '37996-4542', 465.0, Timestamp('2016-03-15 00:00:00'))
(301, '44135-3127', 41.36, Timestamp('2015-12-23 00:00:00'))
(302, '44135-3127', 145.7, Timestamp('2015-12-23 00:00:00'))
(303, '44135-3127', 191.76, Timestamp('2015-12-23 00:00:00'))
(304, '44135-3127', 503.84, Timestamp('2015-12-23 00:00:00'))
(305, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(306, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(307, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(308, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(309, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(310, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(311, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(312, '44135-3127', 785.84, Timestamp('2015-12-23 00:00:00'))
(313, '44135-3127', 814.04, Timestamp('2015-12-23 00:00:00'))
(314, '44135-3127', 871.38, Timestamp('2015-12-23 00:00:00'))
(315, '44135-3127', 1037.76, Timestamp('2015-12-23 00:00:00'))
(316, '44135-3127', 1037.76, Timestamp('2015-12-23 00:00:00'))
(317, '44135-3127', 1294.38, Timestamp('2015-12-23 00:00:00'))
(318, '44135-3127', 1697.64, Timestamp('2015-12-23 00:00:00'))
(319, '44135-3127', 7723.04, Timestamp('2015-12-23 00:00:00'))
(320, '44135-3127', 26462.8, Timestamp('2015-12-23 00:00:00'))
(321, '44135-3127', 58801.7, Timestamp('2015-12-23 00:00:00'))
(322, '46556-5688', 122.0, Timestamp('2016-01-20 00:00:00'))

(323, '48108-2285', 8.0, Timestamp('2015-12-17 00:00:00'))
(324, '48108-2285', 15.0, Timestamp('2016-02-10 00:00:00'))
(325, '48108-2285', 153.0, Timestamp('2015-04-28 00:00:00'))
(326, '48108-2285', 156.0, Timestamp('2015-12-17 00:00:00'))
(327, '48108-2285', 713.68, Timestamp('2016-02-10 00:00:00'))
(328, '48108-2285', 1108.0, Timestamp('2016-02-10 00:00:00'))
(329, '48108-2285', 6045.0, Timestamp('2015-09-25 00:00:00'))
(330, '48108-2285', 46322.06, Timestamp('2016-02-10 00:00:00'))
(331, '48109-1040', 9996.0, Timestamp('2015-09-28 00:00:00'))
(332, '48109-1048', 3441.0, Timestamp('2015-08-19 00:00:00'))
(333, '48109-1048', 3876.0, Timestamp('2015-08-19 00:00:00'))
(334, '48109-1282', 15.0, Timestamp('2015-10-23 00:00:00'))
(335, '48109-1282', 9996.0, Timestamp('2015-10-23 00:00:00'))
(336, '48130-0160', 10224.9, Timestamp('2015-06-05 00:00:00'))
(337, '48130-0160', 25039.0, Timestamp('2015-06-05 00:00:00'))
(338, '48130-0160', 25754.4, Timestamp('2016-01-11 00:00:00'))
(339, '49931-1295', 96.39, Timestamp('2015-07-30 00:00:00'))
(340, '49931-1295', 219.24, Timestamp('2015-07-30 00:00:00'))
(341, '49931-1295', 573.62, Timestamp('2015-07-30 00:00:00'))
(342, '49931-1295', 790.02, Timestamp('2015-07-30 00:00:00'))
(343, '49931-1295', 790.02, Timestamp('2015-07-30 00:00:00'))
(344, '49931-1295', 1519.56, Timestamp('2015-07-30 00:00:00'))
(345, '49931-1295', 6142.5, Timestamp('2015-07-30 00:00:00'))
(346, '49931-1295', 19761.84, Timestamp('2015-07-30 00:00:00'))
(347, '50011-2161', 119.0, Timestamp('2015-08-10 00:00:00'))
(348, '50011-2161', 250.0, Timestamp('2015-08-10 00:00:00'))
(349, '50011-2161', 795.2, Timestamp('2015-08-10 00:00:00'))
(350, '50011-2161', 795.2, Timestamp('2015-08-10 00:00:00'))
(351, '50011-2161', 795.9, Timestamp('2015-08-10 00:00:00'))
(352, '50011-2161', 7351.4, Timestamp('2015-08-10 00:00:00'))
(353, '50011-2161', 24650.0, Timestamp('2015-12-18 00:00:00'))
(354, '50011-2230', 10.0, Timestamp('2015-06-22 00:00:00'))
(355, '50011-2230', 153.0, Timestamp('2015-06-22 00:00:00'))
(356, '53711-4495', 405.0, Timestamp('2016-03-02 00:00:00'))
(357, '53711-4495', 450.0, Timestamp('2015-04-28 00:00:00'))
(358, '53711-4495', 450.0, Timestamp('2015-08-07 00:00:00'))
(359, '53711-4495', 450.0, Timestamp('2015-11-10 00:00:00'))
(360, '53711-4495', 499.0, Timestamp('2015-12-29 00:00:00'))
(361, '53711-4495', 500.0, Timestamp('2016-03-24 00:00:00'))
(362, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(363, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(364, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(365, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(366, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(367, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(368, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(369, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(370, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(371, '53711-4495', 3750.0, Timestamp('2015-06-25 00:00:00'))
(372, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(373, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(374, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(375, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(376, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(377, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(378, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(379, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(380, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(381, '53711-4495', 3750.0, Timestamp('2015-11-24 00:00:00'))
(382, '53711-4495', 3750.0, Timestamp('2016-02-12 00:00:00'))
(383, '53711-4495', 3750.0, Timestamp('2016-02-23 00:00:00'))
(384, '53711-4495', 3750.0, Timestamp('2016-02-23 00:00:00'))
(385, '53711-4495', 3750.0, Timestamp('2016-03-02 00:00:00'))
(386, '53711-4495', 3750.0, Timestamp('2016-03-02 00:00:00'))
(387, '53711-4495', 3750.0, Timestamp('2016-03-10 00:00:00'))
(388, '53711-4495', 3750.0, Timestamp('2016-03-10 00:00:00'))
(389, '53711-4495', 3750.0, Timestamp('2016-03-10 00:00:00'))
(390, '53711-4495', 3750.0, Timestamp('2016-03-10 00:00:00'))
(391, '53711-4495', 3750.0, Timestamp('2016-03-11 00:00:00'))
(392, '53711-4495', 3750.0, Timestamp('2016-03-11 00:00:00'))
(393, '53711-4495', 3750.0, Timestamp('2016-03-11 00:00:00'))
(394, '53711-4495', 3750.0, Timestamp('2016-03-15 00:00:00'))
(395, '53711-4495', 3750.0, Timestamp('2016-03-17 00:00:00'))
(396, '53711-4495', 3750.0, Timestamp('2016-03-17 00:00:00'))
(397, '53711-4495', 3750.0, Timestamp('2016-03-24 00:00:00'))
(398, '53711-4495', 4450.0, Timestamp('2015-05-06 00:00:00'))
(399, '53711-4495', 4672.0, Timestamp('2015-04-13 00:00:00'))
(400, '53711-4495', 4672.0, Timestamp('2015-04-13 00:00:00'))
(401, '53711-4495', 4672.0, Timestamp('2015-04-13 00:00:00'))
(402, '53711-4495', 4672.0, Timestamp('2015-04-13 00:00:00'))
(403, '53711-4495', 4672.0, Timestamp('2015-04-15 00:00:00'))
(404, '53711-4495', 4672.0, Timestamp('2015-04-15 00:00:00'))
(405, '53711-4495', 4672.0, Timestamp('2015-04-17 00:00:00'))
(406, '53711-4495', 4672.0, Timestamp('2015-04-17 00:00:00'))
(407, '53711-4495', 4672.0, Timestamp('2015-04-17 00:00:00'))
(408, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(409, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(410, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(411, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(412, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(413, '53711-4495', 4672.0, Timestamp('2015-04-28 00:00:00'))
(414, '53711-4495', 4672.0, Timestamp('2015-05-19 00:00:00'))
(415, '53711-4495', 4672.0, Timestamp('2015-05-19 00:00:00'))
(416, '53711-4495', 4672.0, Timestamp('2015-05-19 00:00:00'))
(417, '53711-4495', 4672.0, Timestamp('2015-05-19 00:00:00'))
(418, '53711-4495', 4672.0, Timestamp('2015-05-28 00:00:00'))
(419, '53711-4495', 4672.0, Timestamp('2015-05-28 00:00:00'))
(420, '53711-4495', 4672.0, Timestamp('2015-05-28 00:00:00'))
(421, '53711-4495', 4672.0, Timestamp('2015-06-11 00:00:00'))
(422, '53711-4495', 4672.0, Timestamp('2015-06-11 00:00:00'))
(423, '53711-4495', 4672.0, Timestamp('2015-06-22 00:00:00'))
(424, '53711-4495', 4672.0, Timestamp('2015-06-22 00:00:00'))
(425, '53711-4495', 4672.0, Timestamp('2015-06-22 00:00:00'))
(426, '53711-4495', 4672.0, Timestamp('2015-06-22 00:00:00'))
(427, '53711-4495', 4672.0, Timestamp('2015-06-25 00:00:00'))
(428, '53711-4495', 4672.0, Timestamp('2015-06-25 00:00:00'))
(429, '53711-4495', 4672.0, Timestamp('2015-06-25 00:00:00'))
(430, '53711-4495', 4672.0, Timestamp('2015-07-02 00:00:00'))
(431, '53711-4495', 4672.0, Timestamp('2015-07-02 00:00:00'))
(432, '53711-4495', 4672.0, Timestamp('2015-07-02 00:00:00'))
(433, '53711-4495', 4672.0, Timestamp('2015-07-08 00:00:00'))
(434, '53711-4495', 4672.0, Timestamp('2015-07-10 00:00:00'))
(435, '53711-4495', 4672.0, Timestamp('2015-07-15 00:00:00'))
(436, '53711-4495', 4672.0, Timestamp('2015-07-15 00:00:00'))
(437, '53711-4495', 4672.0, Timestamp('2015-08-07 00:00:00'))
(438, '53711-4495', 4672.0, Timestamp('2015-08-10 00:00:00'))
(439, '53711-4495', 4672.0, Timestamp('2015-08-12 00:00:00'))
(440, '53711-4495', 4672.0, Timestamp('2015-08-12 00:00:00'))
(441, '53711-4495', 4672.0, Timestamp('2015-08-26 00:00:00'))
(442, '53711-4495', 4672.0, Timestamp('2015-08-28 00:00:00'))
(443, '53711-4495', 4672.0, Timestamp('2015-09-04 00:00:00'))
(444, '53711-4495', 4672.0, Timestamp('2015-09-04 00:00:00'))
(445, '53711-4495', 4672.0, Timestamp('2015-09-09 00:00:00'))
(446, '53711-4495', 4672.0, Timestamp('2015-09-09 00:00:00'))
(447, '53711-4495', 4672.0, Timestamp('2015-09-09 00:00:00'))
(448, '53711-4495', 4672.0, Timestamp('2015-09-09 00:00:00'))
(449, '53711-4495', 4672.0, Timestamp('2015-09-16 00:00:00'))
(450, '53711-4495', 4672.0, Timestamp('2015-09-16 00:00:00'))
(451, '53711-4495', 4672.0, Timestamp('2015-09-16 00:00:00'))
(452, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(453, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(454, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(455, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(456, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(457, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(458, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(459, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(460, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(461, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(462, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(463, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(464, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(465, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(466, '53711-4495', 4672.0, Timestamp('2015-09-25 00:00:00'))
(467, '53711-4495', 4672.0, Timestamp('2015-10-07 00:00:00'))
(468, '53711-4495', 4672.0, Timestamp('2015-10-27 00:00:00'))
(469, '53711-4495', 4672.0, Timestamp('2015-11-09 00:00:00'))
(470, '53711-4495', 4672.0, Timestamp('2015-11-09 00:00:00'))
(471, '53711-4495', 4672.0, Timestamp('2015-11-09 00:00:00'))
(472, '53711-4495', 4672.0, Timestamp('2015-11-09 00:00:00'))
(473, '53711-4495', 4672.0, Timestamp('2015-11-20 00:00:00'))
(474, '53711-4495', 4672.0, Timestamp('2015-11-24 00:00:00'))
(475, '53711-4495', 4672.0, Timestamp('2015-11-24 00:00:00'))
(476, '53711-4495', 4672.0, Timestamp('2015-11-24 00:00:00'))
(477, '53711-4495', 4672.0, Timestamp('2015-11-25 00:00:00'))
(478, '53711-4495', 4672.0, Timestamp('2015-12-07 00:00:00'))
(479, '53711-4495', 4672.0, Timestamp('2015-12-07 00:00:00'))
(480, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(481, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(482, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(483, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(484, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(485, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(486, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(487, '53711-4495', 4672.0, Timestamp('2015-12-10 00:00:00'))
(488, '53711-4495', 4672.0, Timestamp('2015-12-11 00:00:00'))
(489, '53711-4495', 4672.0, Timestamp('2015-12-11 00:00:00'))
(490, '53711-4495', 4672.0, Timestamp('2015-12-15 00:00:00'))
(491, '53711-4495', 4672.0, Timestamp('2015-12-15 00:00:00'))
(492, '53711-4495', 4672.0, Timestamp('2015-12-15 00:00:00'))
(493, '53711-4495', 4672.0, Timestamp('2016-01-07 00:00:00'))
(494, '53711-4495', 4672.0, Timestamp('2016-01-08 00:00:00'))
(495, '53711-4495', 4672.0, Timestamp('2016-01-08 00:00:00'))
(496, '53711-4495', 4672.0, Timestamp('2016-01-13 00:00:00'))
(497, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(498, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(499, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(500, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(501, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(502, '53711-4495', 4672.0, Timestamp('2016-01-19 00:00:00'))
(503, '53711-4495', 4672.0, Timestamp('2016-01-20 00:00:00'))
(504, '53711-4495', 4672.0, Timestamp('2016-01-20 00:00:00'))
(505, '53711-4495', 4672.0, Timestamp('2016-01-20 00:00:00'))
(506, '53711-4495', 4672.0, Timestamp('2016-01-20 00:00:00'))
(507, '53711-4495', 4672.0, Timestamp('2016-01-21 00:00:00'))
(508, '53711-4495', 4672.0, Timestamp('2016-01-26 00:00:00'))
(509, '53711-4495', 4672.0, Timestamp('2016-02-12 00:00:00'))
(510, '53711-4495', 4672.0, Timestamp('2016-02-12 00:00:00'))
(511, '53711-4495', 4672.0, Timestamp('2016-02-23 00:00:00'))
(512, '53711-4495', 4672.0, Timestamp('2016-02-23 00:00:00'))
(513, '53711-4495', 4672.0, Timestamp('2016-02-23 00:00:00'))
(514, '53711-4495', 4672.0, Timestamp('2016-02-23 00:00:00'))
(515, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(516, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(517, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(518, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(519, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(520, '53711-4495', 4672.0, Timestamp('2016-03-02 00:00:00'))
(521, '53711-4495', 7200.0, Timestamp('2015-11-27 00:00:00'))
(522, '53711-4495', 10800.0, Timestamp('2015-11-27 00:00:00'))
(523, '53711-4495', 20850.0, Timestamp('2015-04-13 00:00:00'))
(524, '53711-4495', 20850.0, Timestamp('2015-07-02 00:00:00'))
(525, '53711-4495', 20850.0, Timestamp('2015-07-02 00:00:00'))
(526, '53711-4495', 20850.0, Timestamp('2015-07-02 00:00:00'))
(527, '53711-4495', 20850.0, Timestamp('2015-07-02 00:00:00'))
(528, '53711-4495', 20850.0, Timestamp('2015-08-14 00:00:00'))
(529, '53711-4495', 20850.0, Timestamp('2015-09-15 00:00:00'))
(530, '53711-4495', 20850.0, Timestamp('2015-09-15 00:00:00'))
(531, '53711-4495', 20850.0, Timestamp('2015-09-25 00:00:00'))
(532, '53711-4495', 20850.0, Timestamp('2015-09-25 00:00:00'))
(533, '53711-4495', 20850.0, Timestamp('2015-09-25 00:00:00'))
(534, '53711-4495', 20850.0, Timestamp('2015-09-25 00:00:00'))
(535, '53711-4495', 20850.0, Timestamp('2015-09-25 00:00:00'))
(536, '53711-4495', 20850.0, Timestamp('2015-11-05 00:00:00'))
(537, '53711-4495', 20850.0, Timestamp('2015-11-09 00:00:00'))
(538, '53711-4495', 20850.0, Timestamp('2015-11-09 00:00:00'))
(539, '53711-4495', 20850.0, Timestamp('2015-11-17 00:00:00'))
(540, '53711-4495', 20850.0, Timestamp('2015-11-24 00:00:00'))
(541, '53711-4495', 20850.0, Timestamp('2015-12-04 00:00:00'))
(542, '53711-4495', 20850.0, Timestamp('2015-12-15 00:00:00'))
(543, '53711-4495', 20850.0, Timestamp('2015-12-23 00:00:00'))
(544, '53711-4495', 20850.0, Timestamp('2015-12-23 00:00:00'))
(545, '53711-4495', 20850.0, Timestamp('2016-01-28 00:00:00'))
(546, '53711-4495', 20850.0, Timestamp('2016-02-05 00:00:00'))
(547, '53711-4495', 20850.0, Timestamp('2016-02-10 00:00:00'))
(548, '53711-4495', 20850.0, Timestamp('2016-02-10 00:00:00'))
(549, '53711-4495', 20850.0, Timestamp('2016-02-12 00:00:00'))
(550, '53711-4495', 20850.0, Timestamp('2016-02-23 00:00:00'))
(551, '53711-4495', 20850.0, Timestamp('2016-02-24 00:00:00'))
(552, '53711-4495', 20850.0, Timestamp('2016-02-25 00:00:00'))
(553, '53711-4495', 20850.0, Timestamp('2016-03-17 00:00:00'))
(554, '53711-4495', 20850.0, Timestamp('2016-03-17 00:00:00'))
(555, '53711-4495', 20850.0, Timestamp('2016-03-29 00:00:00'))
(556, '55112-6999', 15.0, Timestamp('2016-02-10 00:00:00'))

(557, '55112-6999', 536.0, Timestamp('2016-02-10 00:00:00'))
(558, '55112-6999', 28488.6, Timestamp('2016-02-10 00:00:00'))
(559, '55126-3996', 520.0, Timestamp('2015-05-12 00:00:00'))
(560, '55126-3996', 606.0, Timestamp('2015-06-25 00:00:00'))
(561, '55126-3996', 9520.0, Timestamp('2015-05-12 00:00:00'))
(562, '55126-3996', 29700.0, Timestamp('2015-12-23 00:00:00'))
(563, '60064-3537', 536.0, Timestamp('2015-06-03 00:00:00'))
(564, '60085-8320', 8.0, Timestamp('2015-08-19 00:00:00'))
(565, '60085-8320', 265.0, Timestamp('2015-08-19 00:00:00'))
(566, '60439-4832', 194.12, Timestamp('2015-04-15 00:00:00'))
(567, '60439-4832', 1692.8, Timestamp('2015-04-15 00:00:00'))
(568, '61801-3080', 190.4, Timestamp('2015-05-21 00:00:00'))
(569, '61801-3080', 300.0, Timestamp('2015-05-21 00:00:00'))
(570, '61801-3080', 727.2, Timestamp('2015-05-21 00:00:00'))
(571, '61801-3080', 822.4, Timestamp('2015-05-21 00:00:00'))
(572, '61801-3080', 908.8, Timestamp('2015-05-21 00:00:00'))
(573, '61801-3080', 908.8, Timestamp('2015-05-21 00:00:00'))
(574, '61801-3080', 908.8, Timestamp('2015-05-21 00:00:00'))
(575, '61801-3080', 952.0, Timestamp('2015-05-21 00:00:00'))
(576, '61801-3080', 11221.98, Timestamp('2015-05-21 00:00:00'))
(577, '61801-3080', 13504.8, Timestamp('2015-05-21 00:00:00'))
(578, '61801-3080', 19414.78, Timestamp('2015-05-21 00:00:00'))
(579, '63112-1408', -8437.5, Timestamp('2015-10-16 00:00:00'))
(580, '68588-0299', 446.25, Timestamp('2015-05-19 00:00:00'))
(581, '68588-0299', 48585.15, Timestamp('2015-05-19 00:00:00'))
(582, '75390-9050', 8.0, Timestamp('2015-04-13 00:00:00'))
(583, '75390-9050', 158.0, Timestamp('2015-04-13 00:00:00'))
(584, '75390-9111', 1420.0, Timestamp('2015-05-26 00:00:00'))
(585, '77843-3258', 1873.0, Timestamp('2015-10-23 00:00:00'))
(586, '77843-4242', 5156.0, Timestamp('2015-05-20 00:00:00'))
(587, '77843-4242', 5156.0, Timestamp('2015-05-20 00:00:00'))
(588, '80307-3000', -3136.0, Timestamp('2015-05-28 00:00:00'))
(589, '80401-3305', 1101.05, Timestamp('2015-11-24 00:00:00'))
(590, '80401-3305', 1101.05, Timestamp('2015-11-24 00:00:00'))
(591, '80401-3305', 1102.0, Timestamp('2015-11-24 00:00:00'))
(592, '80401-3305', 1415.5, Timestamp('2015-11-24 00:00:00'))
(593, '83844-0903', 50.0, Timestamp('2015-04-30 00:00:00'))
(594, '83844-0903', 918.0, Timestamp('2015-04-30 00:00:00'))
(595, '83844-0903', 24000.0, Timestamp('2015-06-03 00:00:00'))
(596, '84108-1229', 11720.0, Timestamp('2015-04-13 00:00:00'))
(597, '84108-1229', 11720.0, Timestamp('2015-07-24 00:00:00'))
(598, '84108-1229', 11720.0, Timestamp('2015-07-28 00:00:00'))
(599, '84108-1229', 11720.0, Timestamp('2015-08-18 00:00:00'))
(600, '84108-1229', 11720.0, Timestamp('2015-08-27 00:00:00'))
(601, '84108-1229', 11720.0, Timestamp('2015-09-15 00:00:00'))
(602, '84108-1229', 11720.0, Timestamp('2015-09-15 00:00:00'))
(603, '84108-1229', 11720.0, Timestamp('2015-11-16 00:00:00'))
(604, '84108-1229', 11720.0, Timestamp('2015-11-16 00:00:00'))
(605, '84108-1229', 11720.0, Timestamp('2015-11-16 00:00:00'))
(606, '84108-1229', 11720.0, Timestamp('2015-11-16 00:00:00'))
(607, '85719-0521', -9529.6, Timestamp('2016-02-19 00:00:00'))
(608, '85719-4933', 15.0, Timestamp('2016-03-03 00:00:00'))
(609, '85719-4933', 1163.0, Timestamp('2016-03-03 00:00:00'))
(610, '92037-1002', 66.3, Timestamp('2015-12-14 00:00:00'))
(611, '92037-1002', 3712.8, Timestamp('2015-12-14 00:00:00'))
(612, '92093-0955', -7020.0, Timestamp('2016-01-06 00:00:00'))
(613, '92093-0955', -289.44, Timestamp('2016-01-06 00:00:00'))
(614, '92093-0955', -15.0, Timestamp('2016-01-06 00:00:00'))
(615, '93106-9530', 15.0, Timestamp('2016-02-12 00:00:00'))
(616, '93106-9530', 11700.0, Timestamp('2016-02-12 00:00:00'))
(617, '93106-9530', 11700.0, Timestamp('2016-02-12 00:00:00'))
(618, '94035-1000', 1557.5, Timestamp('2015-09-21 00:00:00'))
(619, '94035-1000', 1557.5, Timestamp('2015-09-21 00:00:00'))
(620, '94035-1000', 39721.25, Timestamp('2015-09-21 00:00:00'))
(621, '94035-1000', 39721.25, Timestamp('2015-09-21 00:00:00'))
(622, '94035-1000', 39721.25, Timestamp('2015-09-21 00:00:00'))
(623, '94035-1000', 39721.25, Timestamp('2015-09-21 00:00:00'))
(624, '94158-2517', 172.51, Timestamp('2015-09-25 00:00:00'))
(625, '94158-2517', 440.88, Timestamp('2015-09-25 00:00:00'))
(626, '94158-2517', 835.72, Timestamp('2015-09-25 00:00:00'))
(627, '94158-2517', 881.76, Timestamp('2015-09-25 00:00:00'))
(628, '94158-2517', 1083.12, Timestamp('2015-09-25 00:00:00'))
(629, '94158-2517', 5750.38, Timestamp('2015-09-25 00:00:00'))
(630, '94158-2517', 8177.04, Timestamp('2015-09-25 00:00:00'))
(631, '94158-2517', 10143.67, Timestamp('2015-09-25 00:00:00'))
(632, '94158-2517', 13425.99, Timestamp('2015-09-25 00:00:00'))
(633, '94158-2517', 13577.8, Timestamp('2015-09-25 00:00:00'))
(634, '94158-2517', 18436.87, Timestamp('2015-09-25 00:00:00'))
(635, '94158-2517', 84927.31, Timestamp('2015-09-25 00:00:00'))
(636, '94507-2637', 35.0, Timestamp('2016-02-22 00:00:00'))
(637, '94507-2637', 36.0, Timestamp('2015-04-15 00:00:00'))
(638, '94507-2637', 546.0, Timestamp('2015-04-15 00:00:00'))
(639, '94507-2637', 1437.0, Timestamp('2016-02-22 00:00:00'))
(640, '97330-4239', 498.75, Timestamp('2015-05-20 00:00:00'))
(641, '97330-4239', 498.75, Timestamp('2015-10-27 00:00:00'))
(642, '97330-4239', 1497.2, Timestamp('2015-05-20 00:00:00'))
(643, '97330-4239', 1497.2, Timestamp('2015-10-27 00:00:00'))
(644, '97330-4239', 10640.0, Timestamp('2015-05-20 00:00:00'))
(645, '97330-4239', 10640.0, Timestamp('2015-10-27 00:00:00'))
(646, '97331-5903', 102.85, Timestamp('2015-07-23 00:00:00'))
(647, '97331-5903', 881.45, Timestamp('2015-07-23 00:00:00'))
(648, '97331-5903', 985.15, Timestamp('2015-07-23 00:00:00'))
(649, '97331-5903', 985.15, Timestamp('2015-07-23 00:00:00'))
(650, '97331-5903', 1173.85, Timestamp('2015-07-23 00:00:00'))
(651, '97331-5903', 11427.4, Timestamp('2015-07-23 00:00:00'))
(652, '97331-5903', 27545.1, Timestamp('2015-07-23 00:00:00'))
(653, '98109-1024', 47.22, Timestamp('2016-01-20 00:00:00'))
(654, '98109-1024', 140.0, Timestamp('2015-05-15 00:00:00'))
(655, '98109-1024', 237.09, Timestamp('2016-02-10 00:00:00'))
(656, '98109-1024', 280.96, Timestamp('2016-01-20 00:00:00'))
(657, '98109-1024', 299.06, Timestamp('2016-01-20 00:00:00'))
(658, '98109-1024', 313.48, Timestamp('2016-02-10 00:00:00'))
(659, '98109-1024', 340.7, Timestamp('2016-02-10 00:00:00'))
(660, '98109-1024', 342.46, Timestamp('2016-02-10 00:00:00'))
(661, '98109-1024', 400.0, Timestamp('2016-01-20 00:00:00'))
(662, '98109-1024', 400.0, Timestamp('2016-02-10 00:00:00'))
(663, '98109-1024', 432.85, Timestamp('2016-01-20 00:00:00'))
(664, '98109-1024', 441.51, Timestamp('2016-01-20 00:00:00'))
(665, '98109-1024', 482.95, Timestamp('2016-02-10 00:00:00'))
(666, '98109-1024', 492.61, Timestamp('2016-02-10 00:00:00'))
(667, '98109-1024', 492.61, Timestamp('2016-02-10 00:00:00'))
(668, '98109-1024', 657.93, Timestamp('2016-01-20 00:00:00'))
(669, '98109-1024', 692.56, Timestamp('2016-01-20 00:00:00'))
(670, '98109-1024', 692.56, Timestamp('2016-01-20 00:00:00'))
(671, '98109-1024', 706.73, Timestamp('2016-01-20 00:00:00'))
(672, '98109-1024', 734.09, Timestamp('2016-02-10 00:00:00'))
(673, '98109-1024', 788.53, Timestamp('2016-02-10 00:00:00'))
(674, '98109-1024', 788.53, Timestamp('2016-02-10 00:00:00'))
(675, '98109-1024', 788.53, Timestamp('2016-02-10 00:00:00'))
(676, '98109-1024', 788.53, Timestamp('2016-03-15 00:00:00'))
(677, '98109-1024', 867.27, Timestamp('2016-01-20 00:00:00'))
(678, '98109-1024', 897.18, Timestamp('2016-01-20 00:00:00'))
(679, '98109-1024', 910.56, Timestamp('2016-01-20 00:00:00'))
(680, '98109-1024', 967.67, Timestamp('2016-02-10 00:00:00'))
(681, '98109-1024', 1006.8, Timestamp('2016-02-10 00:00:00'))
(682, '98109-1024', 1039.68, Timestamp('2016-02-10 00:00:00'))
(683, '98109-1024', 1073.04, Timestamp('2016-02-10 00:00:00'))
(684, '98109-1024', 1128.36, Timestamp('2016-02-10 00:00:00'))
(685, '98109-1024', 1173.14, Timestamp('2016-02-10 00:00:00'))
(686, '98109-1024', 1219.85, Timestamp('2016-01-20 00:00:00'))
(687, '98109-1024', 1268.64, Timestamp('2016-01-20 00:00:00'))
(688, '98109-1024', 1361.06, Timestamp('2016-02-10 00:00:00'))
(689, '98109-1024', 1415.5, Timestamp('2016-02-10 00:00:00'))
(690, '98109-1024', 2537.29, Timestamp('2016-01-20 00:00:00'))
(691, '98109-1024', 2830.99, Timestamp('2016-02-10 00:00:00'))
(692, '98109-1024', 4138.0, Timestamp('2016-01-20 00:00:00'))
(693, '98109-1024', 5902.5, Timestamp('2016-01-20 00:00:00'))
(694, '98109-1024', 6585.75, Timestamp('2016-02-10 00:00:00'))
(695, '98109-1024', 6615.0, Timestamp('2016-02-10 00:00:00'))
(696, '98109-1024', 8393.36, Timestamp('2016-01-20 00:00:00'))
(697, '98109-1024', 9645.93, Timestamp('2016-02-10 00:00:00'))
(698, '98109-1024', 10231.0, Timestamp('2016-01-20 00:00:00'))
(699, '98109-1024', 10231.0, Timestamp('2016-01-20 00:00:00'))
(700, '98109-1024', 10372.12, Timestamp('2016-02-10 00:00:00'))
(701, '98109-1024', 11342.24, Timestamp('2016-01-20 00:00:00'))
(702, '98109-1024', 11715.0, Timestamp('2016-02-10 00:00:00'))
(703, '98109-1024', 12655.18, Timestamp('2016-02-10 00:00:00'))
(704, '98109-1024', 13781.16, Timestamp('2016-01-20 00:00:00'))
(705, '98109-1024', 13936.98, Timestamp('2016-01-20 00:00:00'))
(706, '98109-1024', 15837.41, Timestamp('2016-02-10 00:00:00'))
(707, '98109-1024', 16016.54, Timestamp('2016-02-10 00:00:00'))
(708, '98109-1024', 18463.02, Timestamp('2016-01-20 00:00:00'))
(709, '98109-1024', 20402.18, Timestamp('2016-01-20 00:00:00'))
(710, '98109-1024', 20600.23, Timestamp('2016-02-10 00:00:00'))
(711, '98109-1024', 25000.0, Timestamp('2016-01-20 00:00:00'))
(712, '98109-1024', 28224.0, Timestamp('2016-02-10 00:00:00'))
(713, '98109-1024', 33331.81, Timestamp('2016-01-20 00:00:00'))
(714, '98109-1024', 94893.63, Timestamp('2016-02-10 00:00:00'))
(715, '98109-1024', 107141.58, Timestamp('2016-01-20 00:00:00'))
(716, '99164-1120', 41.1, Timestamp('2015-05-28 00:00:00'))

(717, '99164-1120', 41.1, Timestamp('2015-05-28 00:00:00'))
(718, '99164-1120', 189.04, Timestamp('2015-05-28 00:00:00'))
(719, '99164-1120', 189.04, Timestamp('2015-05-28 00:00:00'))
(720, '99164-1120', 225.0, Timestamp('2015-05-28 00:00:00'))
(721, '99164-1120', 225.0, Timestamp('2015-05-28 00:00:00'))
(722, '99164-1120', 293.03, Timestamp('2015-05-28 00:00:00'))
(723, '99164-1120', 405.35, Timestamp('2015-05-28 00:00:00'))
(724, '99164-1120', 608.23, Timestamp('2015-05-28 00:00:00'))
(725, '99164-1120', 608.23, Timestamp('2015-05-28 00:00:00'))
(726, '99164-1120', 781.41, Timestamp('2015-05-28 00:00:00'))
(727, '99164-1120', 854.8, Timestamp('2015-05-28 00:00:00'))
(728, '99164-1120', 854.8, Timestamp('2015-05-28 00:00:00'))
(729, '99164-1120', 903.5, Timestamp('2015-05-28 00:00:00'))
(730, '99164-1120', 1179.0, Timestamp('2015-05-28 00:00:00'))
(731, '99164-1120', 1512.34, Timestamp('2015-05-28 00:00:00'))
(732, '99164-1120', 1512.34, Timestamp('2015-05-28 00:00:00'))
(733, '99164-1120', 1997.28, Timestamp('2015-05-28 00:00:00'))
(734, '99164-1120', 1997.28, Timestamp('2015-05-28 00:00:00'))
(735, '99164-1120', 3147.98, Timestamp('2015-05-28 00:00:00'))
(736, '99164-1120', 3147.98, Timestamp('2015-05-28 00:00:00'))
(737, '99164-1120', 3876.0, Timestamp('2015-10-29 00:00:00'))
(738, '99164-1120', 4476.8, Timestamp('2015-05-28 00:00:00'))
(739, '99164-1120', 4476.8, Timestamp('2015-05-28 00:00:00'))
(740, '99164-1120', 4608.0, Timestamp('2015-05-28 00:00:00'))
(741, '99164-1120', 4608.0, Timestamp('2015-05-28 00:00:00'))
(742, '99164-1120', 5260.0, Timestamp('2015-05-28 00:00:00'))
(743, '99164-1120', 9252.0, Timestamp('2015-05-28 00:00:00'))
(744, '99164-1120', 10150.0, Timestamp('2015-05-28 00:00:00'))
(745, '99164-1120', 10150.0, Timestamp('2015-05-28 00:00:00'))
(746, '99164-1120', 10150.0, Timestamp('2015-05-28 00:00:00'))
(747, '99164-1120', 11109.84, Timestamp('2015-05-28 00:00:00'))
(748, '99164-1120', 11388.99, Timestamp('2015-05-28 00:00:00'))
(749, '99164-1120', 11486.67, Timestamp('2015-05-28 00:00:00'))
(750, '99164-1120', 11704.23, Timestamp('2015-05-28 00:00:00'))
(751, '99164-1120', 11704.23, Timestamp('2015-05-28 00:00:00'))
(752, '99164-1120', 23850.0, Timestamp('2015-05-28 00:00:00'))
(753, '99164-1120', 23850.0, Timestamp('2015-05-28 00:00:00'))
(754, '99164-1120', 55980.4, Timestamp('2015-05-28 00:00:00'))
(755, '99775-7320', 15.0, Timestamp('2016-03-17 00:00:00'))
(756, '99775-7320', 36628.2, Timestamp('2016-03-17 00:00:00'))

In [58]:

#read latitude, longitude and potential
#read cvs or excel file with data
lat_lng_saleAmountFY16 = pd.read_csv('/Users/covarrubiasr/Documents/SalesLogix/Sales_US_FY16_2.csv')
lat_lng_saleAmountFY16.head()

#lat_lng_saleAmountFY16['Amount'].max()
#lat_lng_saleAmountFY16['Amount'].min()

positive_lat_lng_saleAmountFY16 = lat_lng_saleAmountFY16[lat_lng_saleAmountFY16['Amount'] > 0]
positive_lat_lng_saleAmountFY16.head()
positive_lat_lng_saleAmountFY16

          Postal   Latitute   Longitude    Amount   Invoice_Date
0           1002  42.340380  -72.496819    500.00   4/30/15 0:00
1           1605  42.279853  -71.791903    122.00   9/23/15 0:00
2           1605  42.279853  -71.791903    480.00   12/3/15 0:00
3           1605  42.279853  -71.791903  14036.00   12/3/15 0:00
4           1605  42.279853  -71.791903     15.00   12/3/15 0:00
5           1605  42.279853  -71.791903  18050.00   1/13/16 0:00
6           1605  42.279853  -71.791903    416.00   1/13/16 0:00
7           1609  42.297151  -71.839344   9561.33   3/24/16 0:00
8           1609  42.297151  -71.839344   2113.89   3/24/16 0:00
9           1609  42.297151  -71.839344    956.04   3/24/16 0:00
10          1609  42.297151  -71.839344    855.60   3/24/16 0:00
11          1609  42.297151  -71.839344    855.60   3/24/16 0:00
12          1609  42.297151  -71.839344   1006.26   3/24/16 0:00
13          1609  42.297151  -71.839344    862.11   3/24/16 0:00
14          1609  42.297151  -71.839344  53993.01   3/24/16 0:00
15          1609  42.297151  -71.839344   1527.60   3/24/16 0:00
16          1609  42.297151  -71.839344    247.00   3/24/16 0:00
17          1609  42.297151  -71.839344   1711.20   3/24/16 0:00
18          1609  42.297151  -71.839344     20.00   3/24/16 0:00
19          1742  42.452719  -71.370562    525.00   7/30/15 0:00
20          1742  42.452719  -71.370562      8.00   7/30/15 0:00
39          1748  42.225432  -71.548656  28468.00   4/15/15 0:00
40          1748  42.225432  -71.548656  14405.00   4/15/15 0:00
41          1748  42.225432  -71.548656  14405.00   4/15/15 0:00
42          1748  42.225432  -71.548656   9384.00   4/17/15 0:00
43          1748  42.225432  -71.548656   3029.00   4/17/15 0:00
44          1748  42.225432  -71.548656   2984.00   4/17/15 0:00
45          1748  42.225432  -71.548656  28468.00   4/27/15 0:00
46          1748  42.225432  -71.548656  14405.00   4/27/15 0:00
47          1748  42.225432  -71.548656   1920.00   4/29/15 0:00
...          ...        ...         ...       ...            ...
4938  99164-1120  46.728721 -117.154274    854.80   5/28/15 0:00
4939  99164-1120  46.728721 -117.154274    854.80   5/28/15 0:00
4940  99164-1120  46.728721 -117.154274    903.50   5/28/15 0:00
4941  99164-1120  46.728721 -117.154274   1179.00   5/28/15 0:00
4942  99164-1120  46.728721 -117.154274   1512.34   5/28/15 0:00
4943  99164-1120  46.728721 -117.154274   1512.34   5/28/15 0:00
4944  99164-1120  46.728721 -117.154274   1997.28   5/28/15 0:00
4945  99164-1120  46.728721 -117.154274   1997.28   5/28/15 0:00
4946  99164-1120  46.728721 -117.154274   3147.98   5/28/15 0:00
4947  99164-1120  46.728721 -117.154274   3147.98   5/28/15 0:00
4948  99164-1120  46.728721 -117.154274   3876.00  10/29/15 0:00
4949  99164-1120  46.728721 -117.154274   4476.80   5/28/15 0:00
4950  99164-1120  46.728721 -117.154274   4476.80   5/28/15 0:00
4951  99164-1120  46.728721 -117.154274   4608.00   5/28/15 0:00
4952  99164-1120  46.728721 -117.154274   4608.00   5/28/15 0:00
4953  99164-1120  46.728721 -117.154274   5260.00   5/28/15 0:00
4954  99164-1120  46.728721 -117.154274   9252.00   5/28/15 0:00
4955  99164-1120  46.728721 -117.154274  10150.00   5/28/15 0:00
4956  99164-1120  46.728721 -117.154274  10150.00   5/28/15 0:00
4957  99164-1120  46.728721 -117.154274  10150.00   5/28/15 0:00
4958  99164-1120  46.728721 -117.154274  11109.84   5/28/15 0:00
4959  99164-1120  46.728721 -117.154274  11388.99   5/28/15 0:00
4960  99164-1120  46.728721 -117.154274  11486.67   5/28/15 0:00
4961  99164-1120  46.728721 -117.154274  11704.23   5/28/15 0:00
4962  99164-1120  46.728721 -117.154274  11704.23   5/28/15 0:00
4963  99164-1120  46.728721 -117.154274  23850.00   5/28/15 0:00
4964  99164-1120  46.728721 -117.154274  23850.00   5/28/15 0:00
4965  99164-1120  46.728721 -117.154274  55980.40   5/28/15 0:00
4966  99775-7320  64.817070 -147.879280     15.00   3/17/16 0:00
4967  99775-7320  64.817070 -147.879280  36628.20   3/17/16 0:00

[4832 rows x 5 columns]

In [61]:
#positive_lat_lng_saleAmountFY16 = positive_lat_lng_saleAmountFY16.reindex(columns=['Postal','Latitute','Longitude','Amount'])
#positive_lat_lng_saleAmountFY16[['Latitute','Longitude']] = positive_lat_lng_saleAmountFY16[['Latitute','Longitude']].apply(pd.to_numeric)
total_sales_per_postal = positive_lat_lng_saleAmountFY16.groupby(['Postal','Latitute','Longitude'], as_index=False)['Amount'].sum()
total_sales_per_postal.head()
#positive_lat_lng_saleAmountFY16
print(total_sales_per_postal['Postal'] == '1748')

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
Name: Postal, Length: 374, dtype: bool

In [53]:
#select the maximum value for the sample:
total_sales_per_postal.describe()

         Latitute   Longitude        Amount
count  374.000000  374.000000  3.740000e+02
mean    38.926682  -91.076896  9.444308e+04
std      4.849388   21.867892  3.285392e+05
min     20.713224 -156.462863  5.100000e+01
25%     35.890216 -111.114597  2.553625e+03
50%     39.955772  -84.502682  2.136950e+04
75%     42.305325  -75.195393  5.263325e+04
max     64.817070   30.520264  4.589506e+06

In [62]:
import gmaps
import gmaps.datasets 
#get the center of a city
# do geocode for the whole mega city
geocode_result = googleMapsClient.geocode('New York')[0]  # change the name into your city of interest

# get the center of the city
center_lat=geocode_result['geometry']['location']['lat']
center_lng=geocode_result['geometry']['location']['lng']
#print('center=',center_lat,center_lng)




fig = gmaps.figure()
#my_locations = positive_lat_lng_saleAmountFY16[["Latitute","Longitude"]] 
my_locations = total_sales_per_postal[["Latitute","Longitude"]] 
weights = total_sales_per_postal["Amount"] 
fig = gmaps.figure()
fig = gmaps.figure(center = [center_lat,center_lng], zoom_level=6)
fig.add_layer(gmaps.heatmap_layer(my_locations,weights=weights,max_intensity=500000, dissipating=True))
fig

Figure()

locations = positive_lat_lng_saleAmountFY16[["Latitute","Longitude"]]
weights = positive_lat_lng_saleAmountFY16["Amount"]
import gmaps.datasets
fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations)
#,weights=weights) #,max_intensity = 1000000000, point_radius=100,dissipating=True)
fig.add_layer(heatmap_layer)

#import gmaps.datasets
#fig = gmaps.figure()
#fig.add_layer(gmaps.heatmap_layer(locations, weights=weights,max_intensity=1000000))
#heatmap_layer.max_intensity = 100
#heatmap_layer.point_radius = 2
#heatmap_layer.dissipating = True


fig

In [40]:
import gmaps
#function to generate a heatmap
def drawHeatMap(locations, val, zoom, intensity, radius):
    # setting the data and parameters
    heatmap_layer = gmaps.heatmap_layer(locations, val, dissipating = True)
    heatmap_layer.max_intensity = intensity
    heatmap_layer.point_radius = radius
    # draw the heatmap into a figure
    fig = gmaps.figure()
    fig = gmaps.figure(center = [center_lat,center_lng], zoom_level=zoom)
    fig.add_layer(heatmap_layer)
    return fig

#Can create different center locations after showing the whole map
#fig = gmaps.figure(center = [center_lat,center_lng], zoom_level=zoom)

In [41]:
# do geocode for the whole mega city
geocode_result = gmaps.geocode('New York')[0]  # change the name into your city of interest

# get the center of the city
center_lat=geocode_result['geometry']['location']['lat']
center_lng=geocode_result['geometry']['location']['lng']
print('center=',center_lat,center_lng)

AttributeError: 'module' object has no attribute 'geocode'

In [39]:
# set up parameters
zoom=10
intensity=50000
radius=15
sales = total_sales_per_postal['Amount']

# call the function to draw the heatmap
drawHeatMap(my_locations, sales, zoom, intensity, radius)

AttributeError: 'Client' object has no attribute 'heatmap_layer'

In [ ]:
latlng_filename = '/Users/covarrubiasr/Documents/SalesLogix/lat_lng_sage_list.cvs'
if os.path.isfile(latlng_filename): 
    print("filename with lat and long exist \n")
    lat_lng_potential = pd.read_csv('/Users/covarrubiasr/Documents/SalesLogix/lat_lng_sage_list.cvs')
    print("latitude and longitude filename read")
else:
    coords = []
    zipcodes = []


    for idx,zipcode in enumerate(postalcodes[0:999]):
        if len(zipcode) == 5 or len(zipcode) == 10:
            temp_zip = re.search('(\d{5})([- ])?(\d{4})?', zipcode).group(0)

            temp = gmaps.geocode(temp_zip)
            lat = temp[0]['geometry']['location']['lat']
            lng = temp[0]['geometry']['location']['lng']

            print(zipcode,lat,lng,potential[idx])
            
            coords.append((zipcode,lat,lng,potential[idx]))
        else:
            print("not a valid zip code")
            idx =+ 1

    with open(latlng_filename,'wb') as out:
        csv_out=csv.writer(out)
        csv_out.writerow(['Postalcode','Latitute','Longitude','Potential'])
        for row in coords:
            csv_out.writerow(row)